apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: "local"
  hostPath:
    path: "/run/desktop/mnt/host/c/Curso_tecnico/kubernets/app-mercado/mercado/mercado/pods/sqlite"